version: "3.9"
services:
  api:
    build: ./api
    ports:
      - "5000:5000"
    environment:
      - MODEL_NAME=Test
  app:
    build: ./app
    ports:
      - "8080:8080"
  serve:
    build: ./serve
    ports:
      - "80:80"

  